version: "3"
# Register and configure ci runner for gitlab
# author="xiaobo <peterwillcn@gmail.com>"
services:
  runner:
    image: gitlab-runer-docker:latest
    restart: always
    environment:
      - CI_SERVER_URL=
      - RUNNER_TOKEN=
      - RUNNER_DESCRIPTION=
      - BUILDS_DIR=
      - RUNNER_EXECUTOR=docker
      - DOCKER_IMAGE=alpine:latest
      - TLS_VERIFY=false
      - RUN_UNTAGGED=false
      - DOCKER_VOLUMES=/mnt/nfs:/mnt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/gitlab-runner:/home/gitlab-runner/data
